server:
  port: 9999
  servlet:
    context-path: /camunda

logging:
  level:
    com:
      art: debug
spring:
  # current profile
  profiles:
    active: dev
  # config of DataSource
  datasource:
    hikari:
      url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;SQL_MODE=MYSQL
      username: anything
      password: anything